=== cgoudet/Workspace/python/CreateWorkspace.dtd
<!ELEMENT CreateWorkspace (processes,category*)>
<!ATTLIST CreateWorkspace Name CDATA #IMPLIED>

<!ELEMENT processes (#PCDATA) >

<!ELEMENT category (yield*,pdf*,changeVar*,data)>
<!ATTLIST category Name CDATA #IMPLIED>
<!ATTLIST category systFileName CDATA #IMPLIED>

<!ELEMENT yield (#PCDATA)>
<!ATTLIST yield process CDATA #IMPLIED>
<!ATTLIST yield inFileName CDATA #IMPLIED>
<!ATTLIST yield inVarName CDATA #IMPLIED>
<!ATTLIST yield inWSName CDATA #IMPLIED>

<!ELEMENT pdf (#PCDATA)>
<!ATTLIST pdf process CDATA #IMPLIED>
<!ATTLIST pdf inFileName CDATA #IMPLIED>
<!ATTLIST pdf inVarName CDATA #IMPLIED>
<!ATTLIST pdf inWSName CDATA #IMPLIED>

<!ELEMENT changeVar (#PCDATA)>
<!ATTLIST changeVar inName CDATA #IMPLIED>
<!ATTLIST changeVar outName CDATA #IMPLIED>
<!ATTLIST changeVar outVal CDATA #IMPLIED>
<!ATTLIST changeVar scale CDATA #IMPLIED>

<!ELEMENT data (dataFile)* >

<!ELEMENT dataFile (#PCDATA)>
<!ATTLIST dataFile inFileName CDATA #IMPLIED>
<!ATTLIST dataFile varName CDATA #IMPLIED>
<!ATTLIST dataFile weightName CDATA #IMPLIED>
<!ATTLIST dataFile rooCategoryName CDATA #IMPLIED>
<!ATTLIST dataFile rooCategoryIndex CDATA #IMPLIED>
<!ATTLIST dataFile datasetName CDATA #IMPLIED>

=== cgoudet/Workspace/config/DataICHEP2016.xml
<?xml version="1.0" ?>
<!DOCTYPE CreateWorkspace  SYSTEM "/afs/in2p3.fr/home/c/cgoudet/private/Couplings/Workspace/config/CreateWorkspace.dtd">
<CreateWorkspace Name="/sps/atlas/c/cgoudet/Hgam/Couplages/Outputs/DataICHEP2016.root">
  <processes>ggH VBF VH ttH bbH tHjb tWH</processes>
  <category Name="ggH_CenLow" systFileName="/afs/in2p3.fr/home/c/cgoudet/private/Couplings/Workspace/config/DataICHEP2016_syst.xml">
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ggH_SM_ggH_CenLow" process="ggH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VBF_SM_ggH_CenLow" process="VBF"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VH_SM_ggH_CenLow" process="VH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ttH_SM_ggH_CenLow" process="ttH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_bbH_SM_ggH_CenLow" process="bbH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tHjb_SM_ggH_CenLow" process="tHjb"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tWH_SM_ggH_CenLow" process="tWH"/>
    <pdf inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/ModelSignal/RAW/SigSimple_all_shape_categories_DBCB/Individual/SM/res_SM_DoubleCB_workspace.root" inVarName="sigPdf_SM_m125000_c0" invMass="m_yy_m125000_c0" process="all"/>
    <changeVar inName="muCB_SM_m125000_c0" outName="meanCB" systNP="mean"/>
    <changeVar inName="sigmaCB_SM_m125000_c0" outName="sigmaCB" systNP="sigma"/>
    <changeVar inName="mResonance" outName="mHcomb" outVal="125.09"/>
    <changeVar inName="Yield_Signal_ggH_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VBF_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VH_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_ttH_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_bbH_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tHjb_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tWH_SM_ggH_CenLow" outName="yieldSignal" systNP="yield"/>
    <data>
      <dataFile inFileName="/sps/atlas/e/escalier/HGamma/ProductionModes/FromMxAOD/h013/ICHEP_backup/data15/hist-data.root" selectionCut="catCoup_dev==1" selectionVars="catCoup_dev" treeName="tree_selected" varName="m_yy"/>
      <dataFile inFileName="/sps/atlas/e/escalier/HGamma/ProductionModes/FromMxAOD/h013/ICHEP_backup/data16/hist-data.root" selectionCut="catCoup_dev==1" selectionVars="catCoup_dev" treeName="tree_selected" varName="m_yy"/>
    </data>
    <correlatedVar>mHcomb,lumi_2015,lumi_2016,XS13_ggH_yy,XS13_VBF_yy,XS13_VH_yy,XS13_ttH_yy,XS13_bbH_yy,XS13_tHjb_yy,XS13_tWH_yy</correlatedVar>
    <bkg form="expPol2"/>
  </category>
  <category Name="ggH_CenHigh" systFileName="/afs/in2p3.fr/home/c/cgoudet/private/Couplings/Workspace/config/DataICHEP2016_syst.xml">
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ggH_SM_ggH_CenHigh" process="ggH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VBF_SM_ggH_CenHigh" process="VBF"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VH_SM_ggH_CenHigh" process="VH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ttH_SM_ggH_CenHigh" process="ttH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_bbH_SM_ggH_CenHigh" process="bbH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tHjb_SM_ggH_CenHigh" process="tHjb"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tWH_SM_ggH_CenHigh" process="tWH"/>
    <pdf inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/ModelSignal/RAW/SigSimple_all_shape_categories_DBCB/Individual/SM/res_SM_DoubleCB_workspace.root" inVarName="sigPdf_SM_m125000_c1" invMass="m_yy_m125000_c1" process="all"/>
    <changeVar inName="muCB_SM_m125000_c1" outName="meanCB" systNP="mean"/>
    <changeVar inName="sigmaCB_SM_m125000_c1" outName="sigmaCB" systNP="sigma"/>
    <changeVar inName="mResonance" outName="mHcomb" outVal="125.09"/>
    <changeVar inName="Yield_Signal_ggH_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VBF_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VH_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_ttH_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_bbH_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tHjb_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tWH_SM_ggH_CenHigh" outName="yieldSignal" systNP="yield"/>
    <data>
      <dataFile inFileName="/sps/atlas/e/escalier/HGamma/ProductionModes/FromMxAOD/h013/ICHEP_backup/data15/hist-data.root" selectionCut="catCoup_dev==2" selectionVars="catCoup_dev" treeName="tree_selected" varName="m_yy"/>
      <dataFile inFileName="/sps/atlas/e/escalier/HGamma/ProductionModes/FromMxAOD/h013/ICHEP_backup/data16/hist-data.root" selectionCut="catCoup_dev==2" selectionVars="catCoup_dev" treeName="tree_selected" varName="m_yy"/>
    </data>
    <correlatedVar>mHcomb,lumi_2015,lumi_2016,XS13_ggH_yy,XS13_VBF_yy,XS13_VH_yy,XS13_ttH_yy,XS13_bbH_yy,XS13_tHjb_yy,XS13_tWH_yy</correlatedVar>
    <bkg form="expPol2"/>
  </category>
  <category Name="ggH_FwdLow" systFileName="/afs/in2p3.fr/home/c/cgoudet/private/Couplings/Workspace/config/DataICHEP2016_syst.xml">
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ggH_SM_ggH_FwdLow" process="ggH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VBF_SM_ggH_FwdLow" process="VBF"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_VH_SM_ggH_FwdLow" process="VH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_ttH_SM_ggH_FwdLow" process="ttH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_bbH_SM_ggH_FwdLow" process="bbH"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tHjb_SM_ggH_FwdLow" process="tHjb"/>
    <yield inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/workspace_signal_yields_categories.root" inVarName="Yield_Signal_tWH_SM_ggH_FwdLow" process="tWH"/>
    <pdf inFileName="/sps/atlas/c/cgoudet/Hgam/Couplages/Inputs/h012/StatisticsChallenge/h013/inputs/ModelSignal/RAW/SigSimple_all_shape_categories_DBCB/Individual/SM/res_SM_DoubleCB_workspace.root" inVarName="sigPdf_SM_m125000_c2" invMass="m_yy_m125000_c2" process="all"/>
    <changeVar inName="muCB_SM_m125000_c2" outName="meanCB" systNP="mean"/>
    <changeVar inName="sigmaCB_SM_m125000_c2" outName="sigmaCB" systNP="sigma"/>
    <changeVar inName="mResonance" outName="mHcomb" outVal="125.09"/>
    <changeVar inName="Yield_Signal_ggH_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VBF_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_VH_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_ttH_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_bbH_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tHjb_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <changeVar inName="Yield_Signal_tWH_SM_ggH_FwdLow" outName="yieldSignal" systNP="yield"/>
    <data>
      <dataFile inFileName="/sps/atlas/e/escalier/HGamma/ProductionModes/FromMxAOD/h013/ICHEP_backup/data15/hist-data.root" selectionCut="catCoup_dev==3" selectionVars="catCoup_dev" treeName="tree_selected" varName="m_yy"/>
